# inventory.ini
# Lists the machines Ansible will configure. Right now, just the one
# EC2 instance Terraform provisioned. The ansible_ssh_private_key_file
# points at the key Terraform generated for us in Milestone 10.

[sentinel_servers]
sentinel-ec2 ansible_host=3.234.48.52 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/sentinel-key.pem